# Generated by Django 4.0.3 on 2022-03-20 21:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('turn', models.IntegerField(default=1)),
                ('start_time', models.TimeField(default=datetime.time(8, 0))),
                ('period_between_turns', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('sender', models.CharField(max_length=100)),
                ('turn_when_sent', models.IntegerField()),
                ('turn_when_received', models.IntegerField(blank=True, null=True)),
                ('is_lost', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dispatch_backend.channel')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_backend.game')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_backend.game'),
        ),
    ]
