# Generated by Django 4.0.3 on 2022-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentMessage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dispatch_backend.message',),
        ),
        migrations.AddField(
            model_name='game',
            name='has_ended',
            field=models.BooleanField(default=False),
        ),
    ]
