# Generated by Django 4.0.3 on 2022-04-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0002_sentmessage_game_has_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispatch_backend.game')),
            ],
        ),
    ]
