# Generated by Django 4.0.3 on 2022-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0004_alter_category_options_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
