# Generated by Django 4.0.3 on 2022-04-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0005_game_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='server_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
