# Generated by Django 4.0.3 on 2022-04-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0006_alter_game_server_id_alter_game_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
