# Generated by Django 4.0.3 on 2022-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0007_alter_category_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
