# Generated by Django 4.0.3 on 2023-11-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0010_alter_usergamerelation_options_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
