# Generated by Django 4.0.3 on 2023-11-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0011_message_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='message_maximum_length',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='game',
            name='show_sender_in_message',
            field=models.BooleanField(default=True),
        ),
    ]
