# Generated by Django 4.0.3 on 2023-11-19 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0012_game_message_maximum_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='message_maximum_length',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
