# Generated by Django 4.0.3 on 2024-05-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0013_alter_game_message_maximum_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channels',
            field=models.ManyToManyField(related_name='message_channel', to='dispatch_backend.channel'),
        ),
    ]
