# Generated by Django 4.0.3 on 2024-05-01 15:35

from django.db import migrations, models

def populate_channels(apps, schema_editor):
    Message = apps.get_model('dispatch_backend', 'Message')
    for message in Message.objects.all():
        if message.channel is not None:
            message.channels.add(message.channel)
        message.save()

def populate_channel(apps, schema_editor):
    Message = apps.get_model('dispatch_backend', 'Message')
    for message in Message.objects.all():
        message.channel = message.channels.all()[0]
        message.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_backend', '0014_message_channels'),
    ]


    operations = [
        migrations.RunPython(populate_channels, populate_channel)
    ]

